version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - todonet

  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - todonet

volumes:
  db_data: {}

networks:
  todonet:
    driver: bridge